version: '3.8'

services:
  web:
    build: .
    container_name: webgame_php
    network_mode: host
    volumes:
      - .:/var/www/html
    environment:
      - DB_HOST=14.225.219.221
      - DB_USER=dragonboy_user
      - DB_PASS=dragonboy_pass
      - DB_NAME=dragonboy
      - DB_PORT=3306