version: "3.8"
services:
  web:
    build: .
    container_name: webgame_php
    volumes:
      - .:/var/www/html
    environment:
      - DB_HOST=36.50.135.62
      - DB_USER=ahwuocdz
      - DB_PASS=ahwuocdz
      - DB_NAME=nro_1
      - DB_PORT=3306
    ports:
      - "8080:80"
